// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CheckStudent.Repository.Models;

public partial class Course
{
    public int Id { get; set; }

    public string Instructor { get; set; }

    public string InstructorName { get; set; }

    public string Room { get; set; }

    public string Schedule { get; set; }

    public DateTime StartTime { get; set; }

    public DateTime EndTime { get; set; }

    public int SubjectId { get; set; }

    public virtual ICollection<Semester> Semesters { get; set; } = new List<Semester>();

    public virtual ICollection<StudentInCourse> StudentInCourses { get; set; } = new List<StudentInCourse>();

    public virtual Subject Subject { get; set; }
}