// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CheckStudent.Repository.Models;

public partial class Student
{
    public int Id { get; set; }

    public string Code { get; set; }

    public string Name { get; set; }

    public string Email { get; set; }

    public string Phone { get; set; }

    public string Address { get; set; }

    public DateOnly DateOfBirth { get; set; }

    public string Gender { get; set; }

    public string Status { get; set; }

    public virtual ICollection<StudentFace> StudentFaces { get; set; } = new List<StudentFace>();

    public virtual ICollection<StudentInCourse> StudentInCourses { get; set; } = new List<StudentInCourse>();
}